## Global settings ##

# instance id's distinguish stats of multiple relays.
# do not run multiple relays with the same instance id.
# supported variables:
#  ${HOST} : hostname
instance = "${HOST}"

## System ##
# this setting can be used to override the default GOMAXPROCS logic
# it is ignored if the GOMAXPROCS environment variable is set
# max_procs = 2
pid_file = "/tmp/carbon-relay-ng.pid"
# directory for spool files
spool_dir = "/tmp/spool-carbon-relay-ng"

## Logging ##
# one of trace debug info warn error fatal panic
# see docs/logging.md for level descriptions
# note: if you used to use `notice`, you should now use `info`.
log_level = "info"



# How long to keep track of invalid metrics seen
# Useful time units are "s", "m", "h"
bad_metrics_max_age = "24h"

[[inputs]]
type = "kafka"
format = "plain"
topic = "metrics"
brokers = ["kafka:29092"]
consumer_group_id = "aggregator"
commit_interval = "1s"
client_id = "my_carbon"

## Instrumentation ##

[[route]]
key = 'test'
type = 'bg_metadata'
    [route.bg_metadata]
    sharding_factor = 10
    filter_size = 1000
    fault_tolerance = 0.0000001
    clear_interval = "60s"
    cache = "/tmp/"
    storage_schemas = "/config/storage-schemas.conf"
    storage_aggregations = "/config/storage-aggregation.conf"
    storage = "elasticsearch"
        [route.bg_metadata.elasticsearch]
        storage_server = "http://elasticsearch:9200"
        bulk_size = 2
        max_retry = 1
